## Build the code book for the Getting and Cleaning Data course project

## Gather and clean information from files
features = readLines("./UCI HAR Dataset/features_info.txt", n = 49)
signals = features[-c(1:12,30:49)]
variables = features[-c(1:32)]

col_names = colnames(tidy_data_list$mean_std_data) ## gather column names

## Build code book
code_book = vector(mode = "list",length = 88)
code_book = paste0(col_names)

code_book = gsub("subject", "Subject ID 1 through 30 that was tested.", code_book)
code_book = gsub("activity", "Activity performed during test.", code_book)
code_book = gsub("^t", "Timed ", code_book)
code_book = gsub("^f", "Frequency ", code_book)
code_book = gsub("BodyAcc", "Body Acceleration ", code_book)
code_book = gsub("^angle", "Angle between ", code_book)
code_book = gsub("\\.t", "Timed ", code_book)
code_book = gsub("\\.gravity", " and Gravity", code_book)
code_book = gsub("JerkMean\\.", "Jerk Mean", code_book)
code_book = gsub("\\.X", "X", code_book)
code_book = gsub("\\.Y", "Y", code_book)
code_book = gsub("\\.Z", "Z", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("BodyGyroJerkMean", "Body Gyro Jerk Mean", code_book)
code_book = gsub("GravityMean", "Gravity Mean", code_book)
code_book = gsub("\\.mean", "Mean", code_book)
code_book = gsub("\\.\\.X", " on the X axis", code_book)
code_book = gsub("\\.\\.Y", " on the Y axis", code_book)
code_book = gsub("\\.\\.Z", " on the Z axis", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("BodyGyroJerkMean", "Body Gyro Jerk Mean", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("MagMean", "Mag Mean", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("JerkMagMean", "Jerk Mag Mean", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("BodyGyroJerkMean", "Body Gyro Jerk Mean", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("JerkMag", "Jerk Mag", code_book)
code_book = gsub("GravityMean", "Gravity Mean", code_book)
code_book = gsub("\\.mean", "Mean", code_book)
code_book = gsub("\\.\\.X", " on the X axis", code_book)
code_book = gsub("\\.\\.Y", " on the Y axis", code_book)
code_book = gsub("\\.\\.Z", " on the Z axis", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("BodyGyroJerkMean", "Body Gyro Jerk Mean", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("MagMean", "Mag Mean", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("JerkMagMean", "Jerk Mag Mean", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMean", "Body Gyro Mean", code_book)
code_book = gsub("BodyGyroJerkMean", "Body Gyro Jerk Mean", code_book)
code_book = gsub("GravityAccMean", "Gravity Acceleration Mean", code_book)
code_book = gsub("BodyGyroMag", "Body Gyro Mag", code_book)
code_book = gsub("\\.\\.", "", code_book)
code_book = gsub("GravityAccMean", "Gravity Acc Mean", code_book)
code_book = gsub("GravityAccMag", "Gravity Acc Mag", code_book)
code_book = gsub("BodyGyroJerk", "Body Gyro Jerk", code_book)
code_book = gsub("Mean Freq", "Mean Frequency", code_book)
code_book = gsub("JerkMean", "Jerk Mean", code_book)
code_book = gsub("JerkMeanFreq", "Jerk Mean Frequency", code_book)
code_book = gsub("\\.std", " Standard Deviation", code_book)
code_book = gsub("BodyGyro", "Body Gyro", code_book)
code_book = gsub("BodyBody", "Body", code_book)
code_book = gsub("MeanFreq", "Mean Frequency", code_book)
code_book = gsub("Mag", "Magnitude", code_book)
code_book = paste0("\"",col_names,"\"", " is the ", code_book, "\n")